id = "houston"
name = "Houston"
version = "0.1.0"
schema_version = 1
authors = ["hadez8877"]
description = "A theme featuring cool blues, minty greens, and soft purples"
repository = "https://github.com/hadez8877/houston-zed"